remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Nombres y Apellidos
submodulo: Lady Andrea Vargas Clavijo
periodo: 2023-2
url_foto: https://console.firebase.google.com/u/0/project/cesde1-6ed08/storage/cesde1-6ed08.appspot.com/files?hl=es

